#!/bin/sh

### BEGIN INIT INFO
# Provides:             od8
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Enterprise Resource Management software
# Description:          Open ERP is a complete ERP and CRM software.
### END INIT INFO

# ./python/bin/python openerp-server -c openerp-server.conf --logfile=/mnt/sdb/goe7/log/openerp-server.log
# start-stop-daemon --start --quiet --pidfile /home/od8/od.pid --chuid openerp  --background --make-pidfile --exec /home/od8/runtime/python/bin/python -- /home/od8/source/openerp-server -c /home/od8/openerp-server.conf --logfile=/home/od8/log/openerp-server.log
# Specify the user name (Default: openerp).
USER=openerp

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DAEMON=/home/od8/runtime/python/bin/python
NAME=od8
DESC="Green Odoo 8.0"

# Specify an alternate config file (Default: /etc/openerp-server.conf).
CONFIGFILE="/home/od8/openerp-server.conf"

# Specify an alternate log file (Default: /mnt/sdb/goe7/log/openerp-server.log).
LOGFILE="/home/od8/log/openerp-server.log"

# pidfile
#PIDFILE=/var/run/$NAME.pid
PIDFILE=/home/od8/$NAME.pid

# Additional options that are passed to the Daemon.
DAEMON_OPTS="/home/od8/source/openerp-server -c $CONFIGFILE --logfile=$LOGFILE"

# start from dir
DIR=/home/od8


[ -x $DAEMON ] || exit 0
[ -f $CONFIGFILE ] || exit 0

checkpid() {
    [ -f $PIDFILE ] || return 1
    pid=`cat $PIDFILE`
    [ -d /proc/$pid ] && return 0
    return 1
}

case "${1}" in
        start)
                echo -n "Starting ${DESC}: "
                start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
                        --chdir ${DIR} \
                        --chuid ${USER} --background --make-pidfile\
                        --exec ${DAEMON} -- ${DAEMON_OPTS}

                echo "${NAME}."
                ;;

        stop)
                echo -n "Stopping ${DESC}: "

                start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
                        --oknodo

                echo "${NAME}."
                ;;

        restart|force-reload)
                echo -n "Restarting ${DESC}: "

                start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
                        --oknodo
      
                sleep 1

                start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
                        --chdir ${DIR} \
                        --chuid ${USER} --background --make-pidfile \
                        --exec ${DAEMON} -- ${DAEMON_OPTS}

                echo "${NAME}."
                ;;

        *)
                N=/etc/init.d/${NAME}
                echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
                exit 1
                ;;
esac

exit 0
